/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int adV(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int adV_alloc_mem(void);
int adV_init_mem(int mem);
void adV_free_mem(int mem);
int adV_checkout(void);
void adV_release(int mem);
void adV_incref(void);
void adV_decref(void);
casadi_int adV_n_in(void);
casadi_int adV_n_out(void);
casadi_real adV_default_in(casadi_int i);
const char* adV_name_in(casadi_int i);
const char* adV_name_out(casadi_int i);
const casadi_int* adV_sparsity_in(casadi_int i);
const casadi_int* adV_sparsity_out(casadi_int i);
int adV_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int adV_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define adV_SZ_ARG 5
#define adV_SZ_RES 3
#define adV_SZ_IW 0
#define adV_SZ_W 183
int AxisAng3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int AxisAng3_alloc_mem(void);
int AxisAng3_init_mem(int mem);
void AxisAng3_free_mem(int mem);
int AxisAng3_checkout(void);
void AxisAng3_release(int mem);
void AxisAng3_incref(void);
void AxisAng3_decref(void);
casadi_int AxisAng3_n_in(void);
casadi_int AxisAng3_n_out(void);
casadi_real AxisAng3_default_in(casadi_int i);
const char* AxisAng3_name_in(casadi_int i);
const char* AxisAng3_name_out(casadi_int i);
const casadi_int* AxisAng3_sparsity_in(casadi_int i);
const casadi_int* AxisAng3_sparsity_out(casadi_int i);
int AxisAng3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int AxisAng3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define AxisAng3_SZ_ARG 3
#define AxisAng3_SZ_RES 3
#define AxisAng3_SZ_IW 0
#define AxisAng3_SZ_W 4
int AxisAng6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int AxisAng6_alloc_mem(void);
int AxisAng6_init_mem(int mem);
void AxisAng6_free_mem(int mem);
int AxisAng6_checkout(void);
void AxisAng6_release(int mem);
void AxisAng6_incref(void);
void AxisAng6_decref(void);
casadi_int AxisAng6_n_in(void);
casadi_int AxisAng6_n_out(void);
casadi_real AxisAng6_default_in(casadi_int i);
const char* AxisAng6_name_in(casadi_int i);
const char* AxisAng6_name_out(casadi_int i);
const casadi_int* AxisAng6_sparsity_in(casadi_int i);
const casadi_int* AxisAng6_sparsity_out(casadi_int i);
int AxisAng6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int AxisAng6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define AxisAng6_SZ_ARG 4
#define AxisAng6_SZ_RES 4
#define AxisAng6_SZ_IW 0
#define AxisAng6_SZ_W 14
int dddexp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dddexp3_alloc_mem(void);
int dddexp3_init_mem(int mem);
void dddexp3_free_mem(int mem);
int dddexp3_checkout(void);
void dddexp3_release(int mem);
void dddexp3_incref(void);
void dddexp3_decref(void);
casadi_int dddexp3_n_in(void);
casadi_int dddexp3_n_out(void);
casadi_real dddexp3_default_in(casadi_int i);
const char* dddexp3_name_in(casadi_int i);
const char* dddexp3_name_out(casadi_int i);
const casadi_int* dddexp3_sparsity_in(casadi_int i);
const casadi_int* dddexp3_sparsity_out(casadi_int i);
int dddexp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dddexp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dddexp3_SZ_ARG 8
#define dddexp3_SZ_RES 3
#define dddexp3_SZ_IW 0
#define dddexp3_SZ_W 125
int dddlog3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dddlog3_alloc_mem(void);
int dddlog3_init_mem(int mem);
void dddlog3_free_mem(int mem);
int dddlog3_checkout(void);
void dddlog3_release(int mem);
void dddlog3_incref(void);
void dddlog3_decref(void);
casadi_int dddlog3_n_in(void);
casadi_int dddlog3_n_out(void);
casadi_real dddlog3_default_in(casadi_int i);
const char* dddlog3_name_in(casadi_int i);
const char* dddlog3_name_out(casadi_int i);
const casadi_int* dddlog3_sparsity_in(casadi_int i);
const casadi_int* dddlog3_sparsity_out(casadi_int i);
int dddlog3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dddlog3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dddlog3_SZ_ARG 8
#define dddlog3_SZ_RES 3
#define dddlog3_SZ_IW 0
#define dddlog3_SZ_W 133
int ddexp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ddexp3_alloc_mem(void);
int ddexp3_init_mem(int mem);
void ddexp3_free_mem(int mem);
int ddexp3_checkout(void);
void ddexp3_release(int mem);
void ddexp3_incref(void);
void ddexp3_decref(void);
casadi_int ddexp3_n_in(void);
casadi_int ddexp3_n_out(void);
casadi_real ddexp3_default_in(casadi_int i);
const char* ddexp3_name_in(casadi_int i);
const char* ddexp3_name_out(casadi_int i);
const casadi_int* ddexp3_sparsity_in(casadi_int i);
const casadi_int* ddexp3_sparsity_out(casadi_int i);
int ddexp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int ddexp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ddexp3_SZ_ARG 6
#define ddexp3_SZ_RES 3
#define ddexp3_SZ_IW 0
#define ddexp3_SZ_W 90
int ddexp6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ddexp6_alloc_mem(void);
int ddexp6_init_mem(int mem);
void ddexp6_free_mem(int mem);
int ddexp6_checkout(void);
void ddexp6_release(int mem);
void ddexp6_incref(void);
void ddexp6_decref(void);
casadi_int ddexp6_n_in(void);
casadi_int ddexp6_n_out(void);
casadi_real ddexp6_default_in(casadi_int i);
const char* ddexp6_name_in(casadi_int i);
const char* ddexp6_name_out(casadi_int i);
const casadi_int* ddexp6_sparsity_in(casadi_int i);
const casadi_int* ddexp6_sparsity_out(casadi_int i);
int ddexp6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int ddexp6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ddexp6_SZ_ARG 10
#define ddexp6_SZ_RES 4
#define ddexp6_SZ_IW 0
#define ddexp6_SZ_W 293
int ddlog3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ddlog3_alloc_mem(void);
int ddlog3_init_mem(int mem);
void ddlog3_free_mem(int mem);
int ddlog3_checkout(void);
void ddlog3_release(int mem);
void ddlog3_incref(void);
void ddlog3_decref(void);
casadi_int ddlog3_n_in(void);
casadi_int ddlog3_n_out(void);
casadi_real ddlog3_default_in(casadi_int i);
const char* ddlog3_name_in(casadi_int i);
const char* ddlog3_name_out(casadi_int i);
const casadi_int* ddlog3_sparsity_in(casadi_int i);
const casadi_int* ddlog3_sparsity_out(casadi_int i);
int ddlog3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int ddlog3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ddlog3_SZ_ARG 6
#define ddlog3_SZ_RES 3
#define ddlog3_SZ_IW 0
#define ddlog3_SZ_W 90
int ddlog6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int ddlog6_alloc_mem(void);
int ddlog6_init_mem(int mem);
void ddlog6_free_mem(int mem);
int ddlog6_checkout(void);
void ddlog6_release(int mem);
void ddlog6_incref(void);
void ddlog6_decref(void);
casadi_int ddlog6_n_in(void);
casadi_int ddlog6_n_out(void);
casadi_real ddlog6_default_in(casadi_int i);
const char* ddlog6_name_in(casadi_int i);
const char* ddlog6_name_out(casadi_int i);
const casadi_int* ddlog6_sparsity_in(casadi_int i);
const casadi_int* ddlog6_sparsity_out(casadi_int i);
int ddlog6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int ddlog6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define ddlog6_SZ_ARG 10
#define ddlog6_SZ_RES 4
#define ddlog6_SZ_IW 0
#define ddlog6_SZ_W 301
int dexp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dexp3_alloc_mem(void);
int dexp3_init_mem(int mem);
void dexp3_free_mem(int mem);
int dexp3_checkout(void);
void dexp3_release(int mem);
void dexp3_incref(void);
void dexp3_decref(void);
casadi_int dexp3_n_in(void);
casadi_int dexp3_n_out(void);
casadi_real dexp3_default_in(casadi_int i);
const char* dexp3_name_in(casadi_int i);
const char* dexp3_name_out(casadi_int i);
const casadi_int* dexp3_sparsity_in(casadi_int i);
const casadi_int* dexp3_sparsity_out(casadi_int i);
int dexp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dexp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dexp3_SZ_ARG 5
#define dexp3_SZ_RES 3
#define dexp3_SZ_IW 0
#define dexp3_SZ_W 73
int dexp6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dexp6_alloc_mem(void);
int dexp6_init_mem(int mem);
void dexp6_free_mem(int mem);
int dexp6_checkout(void);
void dexp6_release(int mem);
void dexp6_incref(void);
void dexp6_decref(void);
casadi_int dexp6_n_in(void);
casadi_int dexp6_n_out(void);
casadi_real dexp6_default_in(casadi_int i);
const char* dexp6_name_in(casadi_int i);
const char* dexp6_name_out(casadi_int i);
const casadi_int* dexp6_sparsity_in(casadi_int i);
const casadi_int* dexp6_sparsity_out(casadi_int i);
int dexp6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dexp6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dexp6_SZ_ARG 6
#define dexp6_SZ_RES 4
#define dexp6_SZ_IW 0
#define dexp6_SZ_W 283
int dJacobianBody(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dJacobianBody_alloc_mem(void);
int dJacobianBody_init_mem(int mem);
void dJacobianBody_free_mem(int mem);
int dJacobianBody_checkout(void);
void dJacobianBody_release(int mem);
void dJacobianBody_incref(void);
void dJacobianBody_decref(void);
casadi_int dJacobianBody_n_in(void);
casadi_int dJacobianBody_n_out(void);
casadi_real dJacobianBody_default_in(casadi_int i);
const char* dJacobianBody_name_in(casadi_int i);
const char* dJacobianBody_name_out(casadi_int i);
const casadi_int* dJacobianBody_sparsity_in(casadi_int i);
const casadi_int* dJacobianBody_sparsity_out(casadi_int i);
int dJacobianBody_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dJacobianBody_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dJacobianBody_SZ_ARG 7
#define dJacobianBody_SZ_RES 4
#define dJacobianBody_SZ_IW 0
#define dJacobianBody_SZ_W 322
int dlog3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dlog3_alloc_mem(void);
int dlog3_init_mem(int mem);
void dlog3_free_mem(int mem);
int dlog3_checkout(void);
void dlog3_release(int mem);
void dlog3_incref(void);
void dlog3_decref(void);
casadi_int dlog3_n_in(void);
casadi_int dlog3_n_out(void);
casadi_real dlog3_default_in(casadi_int i);
const char* dlog3_name_in(casadi_int i);
const char* dlog3_name_out(casadi_int i);
const casadi_int* dlog3_sparsity_in(casadi_int i);
const casadi_int* dlog3_sparsity_out(casadi_int i);
int dlog3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dlog3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dlog3_SZ_ARG 5
#define dlog3_SZ_RES 3
#define dlog3_SZ_IW 0
#define dlog3_SZ_W 74
int dlog6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int dlog6_alloc_mem(void);
int dlog6_init_mem(int mem);
void dlog6_free_mem(int mem);
int dlog6_checkout(void);
void dlog6_release(int mem);
void dlog6_incref(void);
void dlog6_decref(void);
casadi_int dlog6_n_in(void);
casadi_int dlog6_n_out(void);
casadi_real dlog6_default_in(casadi_int i);
const char* dlog6_name_in(casadi_int i);
const char* dlog6_name_out(casadi_int i);
const casadi_int* dlog6_sparsity_in(casadi_int i);
const casadi_int* dlog6_sparsity_out(casadi_int i);
int dlog6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int dlog6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define dlog6_SZ_ARG 6
#define dlog6_SZ_RES 4
#define dlog6_SZ_IW 0
#define dlog6_SZ_W 283
int exp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int exp3_alloc_mem(void);
int exp3_init_mem(int mem);
void exp3_free_mem(int mem);
int exp3_checkout(void);
void exp3_release(int mem);
void exp3_incref(void);
void exp3_decref(void);
casadi_int exp3_n_in(void);
casadi_int exp3_n_out(void);
casadi_real exp3_default_in(casadi_int i);
const char* exp3_name_in(casadi_int i);
const char* exp3_name_out(casadi_int i);
const casadi_int* exp3_sparsity_in(casadi_int i);
const casadi_int* exp3_sparsity_out(casadi_int i);
int exp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int exp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define exp3_SZ_ARG 5
#define exp3_SZ_RES 3
#define exp3_SZ_IW 0
#define exp3_SZ_W 82
int exp6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int exp6_alloc_mem(void);
int exp6_init_mem(int mem);
void exp6_free_mem(int mem);
int exp6_checkout(void);
void exp6_release(int mem);
void exp6_incref(void);
void exp6_decref(void);
casadi_int exp6_n_in(void);
casadi_int exp6_n_out(void);
casadi_real exp6_default_in(casadi_int i);
const char* exp6_name_in(casadi_int i);
const char* exp6_name_out(casadi_int i);
const casadi_int* exp6_sparsity_in(casadi_int i);
const casadi_int* exp6_sparsity_out(casadi_int i);
int exp6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int exp6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define exp6_SZ_ARG 6
#define exp6_SZ_RES 6
#define exp6_SZ_IW 0
#define exp6_SZ_W 230
int FKinBody(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FKinBody_alloc_mem(void);
int FKinBody_init_mem(int mem);
void FKinBody_free_mem(int mem);
int FKinBody_checkout(void);
void FKinBody_release(int mem);
void FKinBody_incref(void);
void FKinBody_decref(void);
casadi_int FKinBody_n_in(void);
casadi_int FKinBody_n_out(void);
casadi_real FKinBody_default_in(casadi_int i);
const char* FKinBody_name_in(casadi_int i);
const char* FKinBody_name_out(casadi_int i);
const casadi_int* FKinBody_sparsity_in(casadi_int i);
const casadi_int* FKinBody_sparsity_out(casadi_int i);
int FKinBody_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FKinBody_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FKinBody_SZ_ARG 8
#define FKinBody_SZ_RES 6
#define FKinBody_SZ_IW 0
#define FKinBody_SZ_W 408
int FKinSpace(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int FKinSpace_alloc_mem(void);
int FKinSpace_init_mem(int mem);
void FKinSpace_free_mem(int mem);
int FKinSpace_checkout(void);
void FKinSpace_release(int mem);
void FKinSpace_incref(void);
void FKinSpace_decref(void);
casadi_int FKinSpace_n_in(void);
casadi_int FKinSpace_n_out(void);
casadi_real FKinSpace_default_in(casadi_int i);
const char* FKinSpace_name_in(casadi_int i);
const char* FKinSpace_name_out(casadi_int i);
const casadi_int* FKinSpace_sparsity_in(casadi_int i);
const casadi_int* FKinSpace_sparsity_out(casadi_int i);
int FKinSpace_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int FKinSpace_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define FKinSpace_SZ_ARG 8
#define FKinSpace_SZ_RES 6
#define FKinSpace_SZ_IW 0
#define FKinSpace_SZ_W 488
int JacobianBody(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int JacobianBody_alloc_mem(void);
int JacobianBody_init_mem(int mem);
void JacobianBody_free_mem(int mem);
int JacobianBody_checkout(void);
void JacobianBody_release(int mem);
void JacobianBody_incref(void);
void JacobianBody_decref(void);
casadi_int JacobianBody_n_in(void);
casadi_int JacobianBody_n_out(void);
casadi_real JacobianBody_default_in(casadi_int i);
const char* JacobianBody_name_in(casadi_int i);
const char* JacobianBody_name_out(casadi_int i);
const casadi_int* JacobianBody_sparsity_in(casadi_int i);
const casadi_int* JacobianBody_sparsity_out(casadi_int i);
int JacobianBody_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int JacobianBody_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define JacobianBody_SZ_ARG 7
#define JacobianBody_SZ_RES 6
#define JacobianBody_SZ_IW 0
#define JacobianBody_SZ_W 406
int JointTrajectoryTime(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int JointTrajectoryTime_alloc_mem(void);
int JointTrajectoryTime_init_mem(int mem);
void JointTrajectoryTime_free_mem(int mem);
int JointTrajectoryTime_checkout(void);
void JointTrajectoryTime_release(int mem);
void JointTrajectoryTime_incref(void);
void JointTrajectoryTime_decref(void);
casadi_int JointTrajectoryTime_n_in(void);
casadi_int JointTrajectoryTime_n_out(void);
casadi_real JointTrajectoryTime_default_in(casadi_int i);
const char* JointTrajectoryTime_name_in(casadi_int i);
const char* JointTrajectoryTime_name_out(casadi_int i);
const casadi_int* JointTrajectoryTime_sparsity_in(casadi_int i);
const casadi_int* JointTrajectoryTime_sparsity_out(casadi_int i);
int JointTrajectoryTime_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int JointTrajectoryTime_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define JointTrajectoryTime_SZ_ARG 7
#define JointTrajectoryTime_SZ_RES 4
#define JointTrajectoryTime_SZ_IW 0
#define JointTrajectoryTime_SZ_W 30
int MatrixLog3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MatrixLog3_alloc_mem(void);
int MatrixLog3_init_mem(int mem);
void MatrixLog3_free_mem(int mem);
int MatrixLog3_checkout(void);
void MatrixLog3_release(int mem);
void MatrixLog3_incref(void);
void MatrixLog3_decref(void);
casadi_int MatrixLog3_n_in(void);
casadi_int MatrixLog3_n_out(void);
casadi_real MatrixLog3_default_in(casadi_int i);
const char* MatrixLog3_name_in(casadi_int i);
const char* MatrixLog3_name_out(casadi_int i);
const casadi_int* MatrixLog3_sparsity_in(casadi_int i);
const casadi_int* MatrixLog3_sparsity_out(casadi_int i);
int MatrixLog3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MatrixLog3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MatrixLog3_SZ_ARG 5
#define MatrixLog3_SZ_RES 3
#define MatrixLog3_SZ_IW 0
#define MatrixLog3_SZ_W 75
int log3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int log3_alloc_mem(void);
int log3_init_mem(int mem);
void log3_free_mem(int mem);
int log3_checkout(void);
void log3_release(int mem);
void log3_incref(void);
void log3_decref(void);
casadi_int log3_n_in(void);
casadi_int log3_n_out(void);
casadi_real log3_default_in(casadi_int i);
const char* log3_name_in(casadi_int i);
const char* log3_name_out(casadi_int i);
const casadi_int* log3_sparsity_in(casadi_int i);
const casadi_int* log3_sparsity_out(casadi_int i);
int log3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int log3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define log3_SZ_ARG 6
#define log3_SZ_RES 4
#define log3_SZ_IW 0
#define log3_SZ_W 96
int log6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int log6_alloc_mem(void);
int log6_init_mem(int mem);
void log6_free_mem(int mem);
int log6_checkout(void);
void log6_release(int mem);
void log6_incref(void);
void log6_decref(void);
casadi_int log6_n_in(void);
casadi_int log6_n_out(void);
casadi_real log6_default_in(casadi_int i);
const char* log6_name_in(casadi_int i);
const char* log6_name_out(casadi_int i);
const casadi_int* log6_sparsity_in(casadi_int i);
const casadi_int* log6_sparsity_out(casadi_int i);
int log6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int log6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define log6_SZ_ARG 7
#define log6_SZ_RES 5
#define log6_SZ_IW 0
#define log6_SZ_W 220
int MatrixExp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MatrixExp3_alloc_mem(void);
int MatrixExp3_init_mem(int mem);
void MatrixExp3_free_mem(int mem);
int MatrixExp3_checkout(void);
void MatrixExp3_release(int mem);
void MatrixExp3_incref(void);
void MatrixExp3_decref(void);
casadi_int MatrixExp3_n_in(void);
casadi_int MatrixExp3_n_out(void);
casadi_real MatrixExp3_default_in(casadi_int i);
const char* MatrixExp3_name_in(casadi_int i);
const char* MatrixExp3_name_out(casadi_int i);
const casadi_int* MatrixExp3_sparsity_in(casadi_int i);
const casadi_int* MatrixExp3_sparsity_out(casadi_int i);
int MatrixExp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MatrixExp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MatrixExp3_SZ_ARG 4
#define MatrixExp3_SZ_RES 4
#define MatrixExp3_SZ_IW 0
#define MatrixExp3_SZ_W 61
int MatrixExp6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MatrixExp6_alloc_mem(void);
int MatrixExp6_init_mem(int mem);
void MatrixExp6_free_mem(int mem);
int MatrixExp6_checkout(void);
void MatrixExp6_release(int mem);
void MatrixExp6_incref(void);
void MatrixExp6_decref(void);
casadi_int MatrixExp6_n_in(void);
casadi_int MatrixExp6_n_out(void);
casadi_real MatrixExp6_default_in(casadi_int i);
const char* MatrixExp6_name_in(casadi_int i);
const char* MatrixExp6_name_out(casadi_int i);
const casadi_int* MatrixExp6_sparsity_in(casadi_int i);
const casadi_int* MatrixExp6_sparsity_out(casadi_int i);
int MatrixExp6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MatrixExp6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MatrixExp6_SZ_ARG 5
#define MatrixExp6_SZ_RES 5
#define MatrixExp6_SZ_IW 0
#define MatrixExp6_SZ_W 192
int MatrixLog6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int MatrixLog6_alloc_mem(void);
int MatrixLog6_init_mem(int mem);
void MatrixLog6_free_mem(int mem);
int MatrixLog6_checkout(void);
void MatrixLog6_release(int mem);
void MatrixLog6_incref(void);
void MatrixLog6_decref(void);
casadi_int MatrixLog6_n_in(void);
casadi_int MatrixLog6_n_out(void);
casadi_real MatrixLog6_default_in(casadi_int i);
const char* MatrixLog6_name_in(casadi_int i);
const char* MatrixLog6_name_out(casadi_int i);
const casadi_int* MatrixLog6_sparsity_in(casadi_int i);
const casadi_int* MatrixLog6_sparsity_out(casadi_int i);
int MatrixLog6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int MatrixLog6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define MatrixLog6_SZ_ARG 6
#define MatrixLog6_SZ_RES 4
#define MatrixLog6_SZ_IW 0
#define MatrixLog6_SZ_W 182
int NearZero(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int NearZero_alloc_mem(void);
int NearZero_init_mem(int mem);
void NearZero_free_mem(int mem);
int NearZero_checkout(void);
void NearZero_release(int mem);
void NearZero_incref(void);
void NearZero_decref(void);
casadi_int NearZero_n_in(void);
casadi_int NearZero_n_out(void);
casadi_real NearZero_default_in(casadi_int i);
const char* NearZero_name_in(casadi_int i);
const char* NearZero_name_out(casadi_int i);
const casadi_int* NearZero_sparsity_in(casadi_int i);
const casadi_int* NearZero_sparsity_out(casadi_int i);
int NearZero_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int NearZero_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define NearZero_SZ_ARG 3
#define NearZero_SZ_RES 2
#define NearZero_SZ_IW 0
#define NearZero_SZ_W 2
int RpToTrans(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int RpToTrans_alloc_mem(void);
int RpToTrans_init_mem(int mem);
void RpToTrans_free_mem(int mem);
int RpToTrans_checkout(void);
void RpToTrans_release(int mem);
void RpToTrans_incref(void);
void RpToTrans_decref(void);
casadi_int RpToTrans_n_in(void);
casadi_int RpToTrans_n_out(void);
casadi_real RpToTrans_default_in(casadi_int i);
const char* RpToTrans_name_in(casadi_int i);
const char* RpToTrans_name_out(casadi_int i);
const casadi_int* RpToTrans_sparsity_in(casadi_int i);
const casadi_int* RpToTrans_sparsity_out(casadi_int i);
int RpToTrans_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int RpToTrans_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define RpToTrans_SZ_ARG 4
#define RpToTrans_SZ_RES 2
#define RpToTrans_SZ_IW 0
#define RpToTrans_SZ_W 72
int se3ToVec(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int se3ToVec_alloc_mem(void);
int se3ToVec_init_mem(int mem);
void se3ToVec_free_mem(int mem);
int se3ToVec_checkout(void);
void se3ToVec_release(int mem);
void se3ToVec_incref(void);
void se3ToVec_decref(void);
casadi_int se3ToVec_n_in(void);
casadi_int se3ToVec_n_out(void);
casadi_real se3ToVec_default_in(casadi_int i);
const char* se3ToVec_name_in(casadi_int i);
const char* se3ToVec_name_out(casadi_int i);
const casadi_int* se3ToVec_sparsity_in(casadi_int i);
const casadi_int* se3ToVec_sparsity_out(casadi_int i);
int se3ToVec_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int se3ToVec_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define se3ToVec_SZ_ARG 2
#define se3ToVec_SZ_RES 2
#define se3ToVec_SZ_IW 0
#define se3ToVec_SZ_W 20
int so3ToVec(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int so3ToVec_alloc_mem(void);
int so3ToVec_init_mem(int mem);
void so3ToVec_free_mem(int mem);
int so3ToVec_checkout(void);
void so3ToVec_release(int mem);
void so3ToVec_incref(void);
void so3ToVec_decref(void);
casadi_int so3ToVec_n_in(void);
casadi_int so3ToVec_n_out(void);
casadi_real so3ToVec_default_in(casadi_int i);
const char* so3ToVec_name_in(casadi_int i);
const char* so3ToVec_name_out(casadi_int i);
const casadi_int* so3ToVec_sparsity_in(casadi_int i);
const casadi_int* so3ToVec_sparsity_out(casadi_int i);
int so3ToVec_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int so3ToVec_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define so3ToVec_SZ_ARG 2
#define so3ToVec_SZ_RES 2
#define so3ToVec_SZ_IW 0
#define so3ToVec_SZ_W 10
int TransInv(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int TransInv_alloc_mem(void);
int TransInv_init_mem(int mem);
void TransInv_free_mem(int mem);
int TransInv_checkout(void);
void TransInv_release(int mem);
void TransInv_incref(void);
void TransInv_decref(void);
casadi_int TransInv_n_in(void);
casadi_int TransInv_n_out(void);
casadi_real TransInv_default_in(casadi_int i);
const char* TransInv_name_in(casadi_int i);
const char* TransInv_name_out(casadi_int i);
const casadi_int* TransInv_sparsity_in(casadi_int i);
const casadi_int* TransInv_sparsity_out(casadi_int i);
int TransInv_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int TransInv_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define TransInv_SZ_ARG 4
#define TransInv_SZ_RES 4
#define TransInv_SZ_IW 0
#define TransInv_SZ_W 121
int TransToRp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int TransToRp_alloc_mem(void);
int TransToRp_init_mem(int mem);
void TransToRp_free_mem(int mem);
int TransToRp_checkout(void);
void TransToRp_release(int mem);
void TransToRp_incref(void);
void TransToRp_decref(void);
casadi_int TransToRp_n_in(void);
casadi_int TransToRp_n_out(void);
casadi_real TransToRp_default_in(casadi_int i);
const char* TransToRp_name_in(casadi_int i);
const char* TransToRp_name_out(casadi_int i);
const casadi_int* TransToRp_sparsity_in(casadi_int i);
const casadi_int* TransToRp_sparsity_out(casadi_int i);
int TransToRp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int TransToRp_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define TransToRp_SZ_ARG 2
#define TransToRp_SZ_RES 3
#define TransToRp_SZ_IW 0
#define TransToRp_SZ_W 28
int VecTose3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int VecTose3_alloc_mem(void);
int VecTose3_init_mem(int mem);
void VecTose3_free_mem(int mem);
int VecTose3_checkout(void);
void VecTose3_release(int mem);
void VecTose3_incref(void);
void VecTose3_decref(void);
casadi_int VecTose3_n_in(void);
casadi_int VecTose3_n_out(void);
casadi_real VecTose3_default_in(casadi_int i);
const char* VecTose3_name_in(casadi_int i);
const char* VecTose3_name_out(casadi_int i);
const casadi_int* VecTose3_sparsity_in(casadi_int i);
const casadi_int* VecTose3_sparsity_out(casadi_int i);
int VecTose3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int VecTose3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define VecTose3_SZ_ARG 5
#define VecTose3_SZ_RES 3
#define VecTose3_SZ_IW 0
#define VecTose3_SZ_W 108
int VecToso3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int VecToso3_alloc_mem(void);
int VecToso3_init_mem(int mem);
void VecToso3_free_mem(int mem);
int VecToso3_checkout(void);
void VecToso3_release(int mem);
void VecToso3_incref(void);
void VecToso3_decref(void);
casadi_int VecToso3_n_in(void);
casadi_int VecToso3_n_out(void);
casadi_real VecToso3_default_in(casadi_int i);
const char* VecToso3_name_in(casadi_int i);
const char* VecToso3_name_out(casadi_int i);
const casadi_int* VecToso3_sparsity_in(casadi_int i);
const casadi_int* VecToso3_sparsity_out(casadi_int i);
int VecToso3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int VecToso3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define VecToso3_SZ_ARG 4
#define VecToso3_SZ_RES 2
#define VecToso3_SZ_IW 0
#define VecToso3_SZ_W 30
int pRNE_debug(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int pRNE_debug_alloc_mem(void);
int pRNE_debug_init_mem(int mem);
void pRNE_debug_free_mem(int mem);
int pRNE_debug_checkout(void);
void pRNE_debug_release(int mem);
void pRNE_debug_incref(void);
void pRNE_debug_decref(void);
casadi_int pRNE_debug_n_in(void);
casadi_int pRNE_debug_n_out(void);
casadi_real pRNE_debug_default_in(casadi_int i);
const char* pRNE_debug_name_in(casadi_int i);
const char* pRNE_debug_name_out(casadi_int i);
const casadi_int* pRNE_debug_sparsity_in(casadi_int i);
const casadi_int* pRNE_debug_sparsity_out(casadi_int i);
int pRNE_debug_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int pRNE_debug_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define pRNE_debug_SZ_ARG 16
#define pRNE_debug_SZ_RES 9
#define pRNE_debug_SZ_IW 0
#define pRNE_debug_SZ_W 2107
int CoriolisMatrix(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int CoriolisMatrix_alloc_mem(void);
int CoriolisMatrix_init_mem(int mem);
void CoriolisMatrix_free_mem(int mem);
int CoriolisMatrix_checkout(void);
void CoriolisMatrix_release(int mem);
void CoriolisMatrix_incref(void);
void CoriolisMatrix_decref(void);
casadi_int CoriolisMatrix_n_in(void);
casadi_int CoriolisMatrix_n_out(void);
casadi_real CoriolisMatrix_default_in(casadi_int i);
const char* CoriolisMatrix_name_in(casadi_int i);
const char* CoriolisMatrix_name_out(casadi_int i);
const casadi_int* CoriolisMatrix_sparsity_in(casadi_int i);
const casadi_int* CoriolisMatrix_sparsity_out(casadi_int i);
int CoriolisMatrix_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int CoriolisMatrix_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define CoriolisMatrix_SZ_ARG 21
#define CoriolisMatrix_SZ_RES 10
#define CoriolisMatrix_SZ_IW 0
#define CoriolisMatrix_SZ_W 2630
int GravityForces(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int GravityForces_alloc_mem(void);
int GravityForces_init_mem(int mem);
void GravityForces_free_mem(int mem);
int GravityForces_checkout(void);
void GravityForces_release(int mem);
void GravityForces_incref(void);
void GravityForces_decref(void);
casadi_int GravityForces_n_in(void);
casadi_int GravityForces_n_out(void);
casadi_real GravityForces_default_in(casadi_int i);
const char* GravityForces_name_in(casadi_int i);
const char* GravityForces_name_out(casadi_int i);
const casadi_int* GravityForces_sparsity_in(casadi_int i);
const casadi_int* GravityForces_sparsity_out(casadi_int i);
int GravityForces_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int GravityForces_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#define GravityForces_SZ_ARG 21
#define GravityForces_SZ_RES 10
#define GravityForces_SZ_IW 0
#define GravityForces_SZ_W 2580
#ifdef __cplusplus
} /* extern "C" */
#endif
